ntcalc.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <errno.h>
Data Structures
struct data
Typedefs
typedef struct data data_t
Functions
int nethost (int prefix)
int maskpref (uint32_t ntmask)
uint32_t mask (int prefix)
uint32_t netmask (int prefix)
uint32_t wildcard (int prefix)
uint32_t broadcast (uint32_t addr, int prefix)
uint32_t network (uint32_t addr, int prefix)
uint32_t hostmin (uint32_t addr, int prefix)
uint32_t hostmax (uint32_t addr, int prefix)
char * int2string (uint32_t address)
uint32_t string2int (char *address)
data_t * gethosts (uint32_t addr, int prefix)
void display (data_t *current)
Typedef Documentation
data_t
typedef struct data data_t
data type named data_t
Definition at line 37 of file ntcalc.h.
Function Documentation
broadcast()
uint32_t broadcast (uint32_t addr, int prefix)
calculate broadcast address given an IP address and a prefix length. broadcast: address or wildcard
Definition at line 71 of file ntcalc.c.
References mask().
Referenced by main().
 {
   return ((addr & mask(prefix)) | ~mask(prefix)) ;
 }
display()
void display (data_t * first)
display function that take two pointers current and header of list
Definition at line 163 of file ntcalc.c.
References data::address, data::counter, int2string(), and data::next.
{
   data_t *current;
   current = first;
   if (first == NULL)
     {
       printf("The list is empty!\n");
     }
   do
     {
       printf("[%3d]: %15s\n", current->counter,
          int2string(current->address));
       current = current->next;
     }
   while (current);
 }
gethosts()
data_t* gethosts (uint32_t addr, int prefix)
returns a pointer to data_t type, after appending address to the list
returns a current pointer to data_t type, after that gethosts append address to the list
Definition at line 140 of file ntcalc.c.
References data::address, data::counter, mask(), nethost(), and data::next.
 {
   data_t *current, *head;
   int i;
   current = head = NULL;
   for (i=nethost(prefix); i>0; i--){
     current = (data_t *)malloc(sizeof(data_t));
     current->address=((addr  & mask(prefix) )| htonl(i));
     current->counter = i;
     current->next  = head;
     head = current ;
   }
   return current;
 }
hostmax()
uint32_t hostmax (uint32_t addr, int prefix)
returns host max for a specific address and prefix hostmax: broadcast - 1
Definition at line 103 of file ntcalc.c.
References mask().
Referenced by main().
 {
   return (((addr & mask(prefix)) | ~mask(prefix)) - htonl(1));
 }
hostmin()
uint32_t hostmin (uint32_t addr, int prefix)
returns host min for a specific address and prefix hostmin: network + 1
Definition at line 92 of file ntcalc.c.
References mask().
Referenced by main().
 {
   return ((addr  & mask(prefix)) | htonl(1));
 }
int2string()
char* int2string (uint32_t address)
retuns (char *) for an uint32_t address given.
Definition at line 116 of file ntcalc.c.
Referenced by display(), and main().
 {
   struct in_addr inr;
   inr.s_addr=address;
   return inet_ntoa(inr);
 }
mask()
uint32_t mask (int prefix)
creates a netmask from a specified number of bits
Definition at line 40 of file ntcalc.c.
Referenced by broadcast(), gethosts(), hostmax(), hostmin(), main(), and network().
                  {
   return htonl(~((1 << (32 - prefix))- 1));
 }
maskpref()
int maskpref (uint32_t ntmask)
returns prefix of a specific netmask
Definition at line 22 of file ntcalc.c.
Referenced by main().
{
   int i = 0, prefix = 32;
   while ( i < 32) {
     if (!(ntohl(ntmask) & ((2 << i) - 1)))
       prefix--;
     i++;
   }
   return prefix;
 }
nethost()
int nethost (int prefix)
returns number of hosts/nets from a specific prefix hosts/net : 2^(32 - prefix)- 2
Definition at line 12 of file ntcalc.c.
Referenced by gethosts(), and main().
                    {
   return ((1 << (32 - prefix)) - 2);
 }
netmask()
uint32_t netmask (int prefix)
returns the default (canonical) netmask associated with specified IP address. as uint32_teger in network byte order.
Definition at line 50 of file ntcalc.c.
Referenced by main().
 {
   return htonl(0x00 - (1<<(32 - prefix)));
 }
network()
uint32_t network (uint32_t addr, int prefix)
calculates the network address for a specified address and prefix. network: address and netmask
Definition at line 82 of file ntcalc.c.
References mask().
Referenced by main().
 {
   return (addr & mask(prefix));
 }
string2int()
uint32_t string2int (char * address)
returns an uint32_t from a string address given.
Definition at line 129 of file ntcalc.c.
Referenced by main().
 {
   return inet_addr(address);
 }
wildcard()
uint32_t wildcard (int prefix)
returns the default wildcard associated with specifed prefix
Definition at line 60 of file ntcalc.c.
Referenced by main().
 {
   return htonl(0xFFFFFFFF +  (1<<(32 - prefix)));
 }